fix #38

diff --git a/vimv b/vimv
--- a/vimv
+++ b/vimv
@@ -22,9 +22,15 @@ done
 ${EDITOR:-vi} "${FILENAMES_FILE}"
 
 IFS=$'\r\n' GLOBIGNORE='*' command eval 'dest=($(cat "${FILENAMES_FILE}"))'
+IFS=$'\r\n' GLOBIGNORE='*' command eval 'dest_unique=($(cat "${FILENAMES_FILE}" | sort -u))'
 
 if (( ${#src[@]} != ${#dest[@]} )); then
     echo "WARN: Number of files changed. Did you delete a line by accident? Aborting.." >&2
+    exit 1
+fi
+
+if (( ${#dest[@]} != ${#dest_unique[@]} )); then
+    echo "WARN: Destination filenames are not unique! Aborting.." >&2
     exit 1
 fi
 
